#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind": "Service", "metadata":{"name":"argocd-server"}})
---
spec:
  #@overlay/match missing_ok=True
  type: #@ data.values.service_type
