#@ load("@ytt:data", "data")

#@ def labels():
app: hello-app
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: hello-app
spec:
  ports:
  - port: #@ data.values.service_port
    targetPort: 80
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: hello-app
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: hello-app
        image: docker.io/dkalinin/k8s-simple-app@sha256:4c8b96d4fffdfae29258d94a22ae4ad1fe36139d47288b8960d9958d1e63a9d0
        env:
        - name: HELLO_MSG
          value: #@ data.values.hello_msg
