---
apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
  namespace: my-namespace
spec:
  limits:
    - default:
        cpu: 500m
      defaultRequest:
        cpu: 100m
      type: Container
